apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 817757596025.dkr.ecr.ap-northeast-2.amazonaws.com/schedulechecker_be_auth
  newName: 817757596025.dkr.ecr.ap-northeast-2.amazonaws.com/schedulechecker_be_auth
  newTag: e5ee65dd
- name: 817757596025.dkr.ecr.ap-northeast-2.amazonaws.com/schedulechecker_be_home
  newName: 817757596025.dkr.ecr.ap-northeast-2.amazonaws.com/schedulechecker_be_home
  newTag: 532eb259
- name: 817757596025.dkr.ecr.ap-northeast-2.amazonaws.com/schedulechecker_fe
  newName: 817757596025.dkr.ecr.ap-northeast-2.amazonaws.com/schedulechecker_fe
  newTag: e5ee65dd
resources:
- ../../base
patchesStrategicMerge:
- toy-be-home-patch.yaml
- toy-be-auth-patch.yaml
- toy-fe-patch.yaml
- toy-backend-service-patch.yaml
- toy-ingress-patch.yaml
